services:
  consul:
    image: hashicorp/consul:1.21
    container_name: consul-gula
    ports:
      - "8500:8500"   # UI web de Consul
      - "8600:8600/udp" # DNS de Consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: agent -dev -client=0.0.0.0
    restart: unless-stopped